# The serial port to use:
port: '/dev/cu.usbmodem143301'
settings_file_path: '/dev/shm/settings.txt'

# list of observables to expect from the get_all function call
# The returned dict will use those as keys. Order matters.
get_all_fields:
  - pressure
  - flow
  - o2
  - bpm
  - tidal
  - peep
  - temperature
  - battery_powered
  - battery_charge

# Conversion factors to apply to the values from the get_all
conversions:
    pressure: 1.01972 # mbar to cmH2O
    peak: 1.01972 # mbar to cmH2O

# watchdog reset interval time in seconds
wdinterval: 1

# Time interval used to check for alarms
alarminterval: 1

# Number of samples to display in the graphs:
nsamples: 100

# time in seconds between two data retrieval
sampling_interval: 0.1

# The parameters that can be set on the ESP
# The values below must match those used in the ESP
esp_settable_param:
    respiratory_rate:  'rate'
    insp_expir_ratio:  'ratio'
    insp_pressure:     'ptarget'
    pressure_trigger:  'assist_ptrigger'
    flow_trigger:      'assist_flow_min'
    support_pressure:  'TODO'
    enable_backup:     'backup_enable'
    minimal_resp_rate: 'backup_min_rate'


# This is the string returned by the ESP in case of success
return_success_code: 'OK'

# The interval used to send 1 to the ESP if expiration or espiration 
# paused button is pressed (in seconds)
expinsp_setinterval: 0.1 

# Thickness of the lines drawn in the plots
line_width: 1

# The widht of the line that draws the axes
axis_line_width: 1

# The color used to draw the axes
axis_line_color: "rgb(255,228,181)"

# Shows the values that will trigger the alarms directly on the plots
show_safe_ranges_on_graphs: True

# Toggles the x axis labels in the graphs (specifcally, the 'Time [s]' label)
show_x_axis_labels: True

# Toggles the x axis ticks in the graphs (specifcally, the numbers on the x axis)
show_x_axis_ticks: True

# Toggles between scrolling plots and looping plots
use_looping_plots: False

# Control Start/Stop Auto/Man behavior
start_mode_timeout: 2000 # [ms] between pressing Start and allowing Stop (max 3000)


# Setup monitors (key value monitor_* must match widget name in mainwindow.ui)
# Variables to display in the graphs are in plot_var 
# and the must match names in the ESP or an available function
#
#
monitors:
    inspiratory_pressure: 
        name: "Insp. Press."
        init: 30
        step: 1
        dec_precision: 0
        units: "(cmH<sub>2</sub>O)"
        color: "rgb(255,255,0)"
        alarmcolor: "red"
        observable: pressure

    tidal_volume: 
        name: "v<sub>tidal</sub>"
        init: 100
        step: 100
        dec_precision: 0
        units: "(ml)"
        color: "rgb(50,205,50)"
        alarmcolor: "red"
        observable: tidal

    beats_per_minute: 
        name: "BPM"
        init: 60
        step: 1
        dec_precision: 0
        color: "rgb(50,205,50)"
        alarmcolor: "red"
        observable: bpm

    peep: 
        name: "PEEP"
        init: 60
        step: 1
        dec_precision: 0
        color: "rgb(0,255,255)"
        alarmcolor: "red"
        observable: peep

    battery: 
        name: "Battery"
        init: 100 
        step: 1
        units: "(%)"
        dec_precision: 0
        color: "rgb(0,255,255)"
        alarmcolor: "red"
        observable: battery_charge

    flow: 
        name: "MVe"
        init: 10
        step: 1
        dec_precision: 0
        units: "(slpm)"
        color: "rgb(0,255,255)"
        alarmcolor: "red"
        observable: flow

    oxygen_concentration: 
        name: "O<sub>2</sub> Conc." 
        init: 40
        step: 1
        dec_precision: 0
        units: "(%)"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: o2

    temperature: 
        name: "Temperature" 
        init: 40
        step: 1
        dec_precision: 0
        units: "(C)"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: temperature

    peak: 
        name: "PEAK" 
        init: 40
        step: 1
        dec_precision: 0
        units: "(cmH<sub>2</sub>O)"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: peak

displayed_monitors:
    - inspiratory_pressure
    - tidal_volume
    - flow
    - oxygen_concentration
    - beats_per_minute

alarms:
    o2:
        min: 17
        max: 98 
        setmin: 21
        setmax: 100
        under_threshold_code: 65536
        over_threshold_code: 131072
        observable: o2
        linked_monitor: oxygen_concentration
    
    pressure:
        min: 10
        setmin: 15
        max: 80
        setmax: 75
        under_threshold_code: 256
        over_threshold_code: 512
        observable: pressure
        linked_monitor: inspiratory_pressure

    flow:
        min: 2 
        max: 20
        under_threshold_code: 1024
        over_threshold_code: 2048
        observable: flow
        linked_monitor: flow

    tidal_volume:
        min: 50
        max: 1500
        under_threshold_code: 16384
        over_threshold_code: 32768
        observable: tidal
        linked_monitor: tidal_volume

    bpm:
        min: 5
        max: 10
        under_threshold_code: 1048576
        over_threshold_code: 2097152
        observable: bpm
        linked_monitor: beats_per_minute

    peep:
        min: null
        max: null
        under_threshold_code: 262144
        over_threshold_code: 524288
        observable: peep
        linked_monitor: peep

    battery_charge:
        min: 10
        max: null
        under_threshold_code: 16
        over_threshold_code: null
        observable: battery_charge
        linked_monitor: battery

plots:
    plot_top: 
        name: "Insp. Press."
        min: 10
        max: 80
        units: "(cmH<sub>2</sub>O)"
        color: "rgb(255,255,0)"
        observable: pressure

    plot_mid: 
        name: "v<sub>tidal</sub>"
        min: 50
        max: 1500
        units: "(ml)"
        color: "rgb(50,205,50)"
        observable: tidal

    plot_bot: 
        name: "MVe"
        min: 2 
        max: 20
        units: "(slpm)"
        color: "rgb(0,255,255)"
        observable: flow
#
# Automatic Mode
#
# Note: can only have max 6 presets for now.

# Respiration Rate (breaths per minute)
respiratory_rate:
    name: "Resp. Rate"
    default: 12
    min: 4
    max: 50
    step: 1
    current: None
    units: "b/min"
    presets:
        - [5, '']
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']

# Inspiration/Expiration
insp_expir_ratio:
    # NOTE: this value is always the inverse of the fruction
    name: "Insp./Expir."
    default: 2
    min: 1
    max: 3
    step: 0.01
    current: None
    units: "ratio"
    show_fraction: True
    presets:
      - [1, '1:1'] # 1:1
      - [2, '1:2'] # 1:2
      - [3, '1:3'] # 1:3

# Inspiratory Pressure
insp_pressure:
    name: "Insp. Pressure"
    default:  15
    min: 0
    max: 40
    current: None
    units: "(cmH<sub>2</sub>O)"
    conversion: 0.980665 # From cmH2O to mbar
    presets:
        - [5, '']
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']

# PEEP (auto mode)
#peep_auto:
#    name: "PEEP (Auto)"
#    default:  7.5
#    min: 0
#    max: 20
#    current: None
#    units: "mbar"
#    conversion: 0.980665 # From cmH2O to mbar
#    presets:
#        - [2, '']
#        - [5, '']
#        - [7.5, '']
#        - [10, '']
#        - [15, '']


#
# Assisted Mode
#
# Note: can only have max 6 presets for now.

# The trigger that starts the respiration
pressure_trigger: 
    name: "Pressure Trigger"
    default: 1.
    min: 0.
    max: 90.
    current: None
    presets:
        - [80, 'Hard']
        - [60, 'Medium']
        - [30, 'Normal']
        - [10, 'Soft']


# Flow Trigger
flow_trigger: 
    name: "Flow Trigger"
    default: 20.
    min: 0.
    max: 40.
    current: None
    presets:
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']
        - [35, '']

# Support Pressure
support_pressure:
    name: "Support Pressure"
    default: 10.
    min: 0.
    max: 40.
    current: None
    units: "(cmH<sub>2</sub>O)"
    conversion: 0.980665 # From cmH2O to mbar
    presets:
        - [5, '']
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']

# PEEP Assist
#peep_assist:
#    name: "PEEP (Assist)"
#    default: 7.5
#    min: 0.
#    max: 20.
#    current: None
#    units: "mbar"
#    presets:
#        - [2, '']
#        - [5, '']
#        - [7.5, '']
#        - [10, '']
#        - [15, '']

# Minimal Respiratory Rate
minimal_resp_rate:
    default: 10.
    min: 0.
    max: 20.
    current: None
    presets:
        - [3, '']
        - [5, '']
        - [10, '']
        - [15, '']


# Enable backup
enable_backup: 
  default: 1
  current: None
  presets:
    - [1, "Enabled"]
    - [0, "Disabled"]
