# The serial port to use:
port: '/dev/cu.usbmodem141301'

# If false, opens the GUI but doesn't read data:
read_from_esp: True

# Number of samples to display in the graphs:
nsamples: 100

# time in seconds between two data retrieval
sampling_interval: 0.1

# Variables to display in the graphs (must match names in the ESP):
plot_top_var: mve
plot_mid_var: vti
plot_bot_var: vte

# Control Start/Stop Auto/Man behavior
start_mode_timeout: 2000 # [ms] between pressing Start and allowing Stop (max 3000)

# Setup monitors (key value monitor_* must match widget name in mainwindow.ui)
monitor_top: 
    name: "RR"
    min: 5
    init: 12
    max: 30
    units: "(b/min)"
    color: "black"
    alarmcolor: "red"

monitor_mid: 
    name: "O<sub>2</sub>"
    min: 35
    init: 41
    max: 45
    units: "%"
    color: "blue"
    alarmcolor: "red"

monitor_bot: 
    name: "MVe"
    min: 50
    init: 71
    max: 400
    units: "(l/min)"
    color: "green"
    alarmcolor: "red"
